export const ROUTE_HOME = '/'
export const ROUTE_CAPTURE = '/nuivu'
export const ROUTE_SEARCH = '/busqueda'
export const ROUTE_RESULT = '/palabra'
export const ROUTE_SEARCH_PATTERN = ROUTE_SEARCH+'?q=:query'
export const ROUTE_RESULT_PATTERN = ROUTE_RESULT+'?h=:hash'